Repository Mars-98/chessApp, pull requests merged in 2020-05, with the labels that each got.

#2 Testing
  .gitignore
  window.py
Labels: UI, enhancement

#6 #76ebaj #78gqnh Made the clickable chessboard
  .gitignore
  chess-ui/chessboard/chessboard.py
  chess-ui/chessboard/tile.py
  chess-ui/chessboard/tiles.py
  chess-ui/design_ui/ChessboardIndexing.jpg
  chess-ui/window.py
Labels: UI, enhancement

#7 Design_api
  chess-api/design/brainstorm
  chess-api/design/design_api
Labels: API, documentation

#8 Parent piece
  chess-api/parentPiece/parentPiece.py
Labels: API

#12 Parent piece
  chess-api/parentPiece/piece.py
Labels: API, duplicate

#11 Ui pieces design
  chess-ui/chessboard_parts/bit_pieces/chess_piece_2_black_bishop.bmp
  chess-ui/chessboard_parts/bit_pieces/chess_piece_2_black_king.bmp
  chess-ui/chessboard_parts/bit_pieces/chess_piece_2_black_knight.bmp
  chess-ui/chessboard_parts/bit_pieces/chess_piece_2_black_pawn.bmp
  chess-ui/chessboard_parts/bit_pieces/chess_piece_2_black_queen.bmp
  chess-ui/chessboard_parts/bit_pieces/chess_piece_2_black_rook.bmp
  chess-ui/chessboard_parts/bit_pieces/chess_piece_2_white_bishop.bmp
  chess-ui/chessboard_parts/bit_pieces/chess_piece_2_white_king.bmp
  chess-ui/chessboard_parts/bit_pieces/chess_piece_2_white_knight.bmp
  chess-ui/chessboard_parts/bit_pieces/chess_piece_2_white_pawn.bmp
  chess-ui/chessboard_parts/bit_pieces/chess_piece_2_white_queen.bmp
  chess-ui/chessboard_parts/bit_pieces/chess_piece_2_white_rook.bmp
  chess-ui/chessboard_parts/chessboard.py
  chess-ui/chessboard_parts/pieceTypes/bishop.py
  chess-ui/chessboard_parts/pieceTypes/king.py
  chess-ui/chessboard_parts/pieceTypes/knight.py
  chess-ui/chessboard_parts/pieceTypes/pawn.py
  chess-ui/chessboard_parts/pieceTypes/queen.py
  chess-ui/chessboard_parts/pieceTypes/rook.py
  chess-ui/chessboard_parts/pieces.py
Labels: UI, enhancement

#14 Adding the outline of pieces
  chess-ui/chessboard_parts/bit_pieces/chess_piece_2_black_bishop.bmp
  chess-ui/chessboard_parts/bit_pieces/chess_piece_2_black_king.bmp
  chess-ui/chessboard_parts/bit_pieces/chess_piece_2_black_knight.bmp
  chess-ui/chessboard_parts/bit_pieces/chess_piece_2_black_pawn.bmp
  chess-ui/chessboard_parts/bit_pieces/chess_piece_2_black_queen.bmp
  chess-ui/chessboard_parts/bit_pieces/chess_piece_2_black_rook.bmp
  chess-ui/chessboard_parts/bit_pieces/chess_piece_2_white_bishop.bmp
  chess-ui/chessboard_parts/bit_pieces/chess_piece_2_white_king.bmp
  chess-ui/chessboard_parts/bit_pieces/chess_piece_2_white_knight.bmp
  chess-ui/chessboard_parts/bit_pieces/chess_piece_2_white_pawn.bmp
  chess-ui/chessboard_parts/bit_pieces/chess_piece_2_white_queen.bmp
  chess-ui/chessboard_parts/bit_pieces/chess_piece_2_white_rook.bmp
  chess-ui/chessboard_parts/chessboard.py
  chess-ui/chessboard_parts/pieceTypes/bishop.py
  chess-ui/chessboard_parts/pieceTypes/king.py
  chess-ui/chessboard_parts/pieceTypes/knight.py
  chess-ui/chessboard_parts/pieceTypes/pawn.py
  chess-ui/chessboard_parts/pieceTypes/queen.py
  chess-ui/chessboard_parts/pieceTypes/rook.py
  chess-ui/chessboard_parts/pieces.py
  chess-ui/chessboard_parts/tile.py
  chess-ui/chessboard_parts/tiles.py
  chess-ui/window.py
Labels: UI, enhancement
