Repository Mars-98/chessApp, pull requests merged in 2020-06, with the labels that each got.

#15 Putting each piece on the ui
  chess-ui/chessboard_parts/chessboard.py
  chess-ui/chessboard_parts/pieceTypes/bishop.py
  chess-ui/chessboard_parts/pieceTypes/king.py
  chess-ui/chessboard_parts/pieceTypes/knight.py
  chess-ui/chessboard_parts/pieceTypes/pawn.py
  chess-ui/chessboard_parts/pieceTypes/queen.py
  chess-ui/chessboard_parts/pieceTypes/rook.py
  chess-ui/chessboard_parts/pieces.py
  chess-ui/main.py
Labels: UI, enhancement

#18 Does this cut off the dragon's head?
  chess-ui/main.py
Labels: documentation, help wanted, question

#17 Ui pieces potential moves
  chess-ui/chessboard_parts/chessboard.py
  chess-ui/chessboard_parts/pieceTypes/bishop.py
  chess-ui/chessboard_parts/pieceTypes/king.py
  chess-ui/chessboard_parts/pieceTypes/knight.py
  chess-ui/chessboard_parts/pieceTypes/pawn.py
  chess-ui/chessboard_parts/pieceTypes/queen.py
  chess-ui/chessboard_parts/pieceTypes/rook.py
  chess-ui/chessboard_parts/pieces.py
  chess-ui/chessboard_parts/tile.py
  chess-ui/chessboard_parts/tiles.py
  chess-ui/main.py
  chess-ui/window.py
Labels: UI, enhancement

#19 Parent piece
  chess-api/parentPiece/piece.py
Labels: API

#20 ChessWindow now has self
  chess-ui/main.py
  chess-ui/window.py
Labels: UI, tech debt

#21 Dictionary of tiles for backend
  chess-ui/chessboard_parts/tiles.py
Labels: API, enhancement

#22 Parent piece and king class
  chess-api/childPiece/king.py
  chess-api/parentPiece/piece.py
Labels: API

#25 Retrieve player names via text fields
  .gitignore
  chess-ui/main.py
  chessapi/childPiece/king.py
  chessapi/design/brainstorm
  chessapi/design/design_api
  chessapi/parentPiece/piece.py
  chessui/bit_pieces/chess_piece_2_black_bishop.bmp
  chessui/bit_pieces/chess_piece_2_black_king.bmp
  chessui/bit_pieces/chess_piece_2_black_knight.bmp
  chessui/bit_pieces/chess_piece_2_black_pawn.bmp
  chessui/bit_pieces/chess_piece_2_black_queen.bmp
  chessui/bit_pieces/chess_piece_2_black_rook.bmp
  chessui/bit_pieces/chess_piece_2_white_bishop.bmp
  chessui/bit_pieces/chess_piece_2_white_king.bmp
  chessui/bit_pieces/chess_piece_2_white_knight.bmp
  chessui/bit_pieces/chess_piece_2_white_pawn.bmp
  chessui/bit_pieces/chess_piece_2_white_queen.bmp
  chessui/bit_pieces/chess_piece_2_white_rook.bmp
  chessui/chessboardparts/chess_pieces_bitmap/black_bishop.bmp
  chessui/chessboardparts/chess_pieces_bitmap/black_king.bmp
  chessui/chessboardparts/chess_pieces_bitmap/black_knight.bmp
  chessui/chessboardparts/chess_pieces_bitmap/black_pawn.bmp
  chessui/chessboardparts/chess_pieces_bitmap/black_queen.bmp
  chessui/chessboardparts/chess_pieces_bitmap/black_rook.bmp
  chessui/chessboardparts/chess_pieces_bitmap/white_bishop.bmp
  chessui/chessboardparts/chess_pieces_bitmap/white_king.bmp
  chessui/chessboardparts/chess_pieces_bitmap/white_knight.bmp
  chessui/chessboardparts/chess_pieces_bitmap/white_pawn.bmp
  chessui/chessboardparts/chess_pieces_bitmap/white_queen.bmp
  chessui/chessboardparts/chess_pieces_bitmap/white_rook.bmp
  chessui/chessboardparts/chessboard.py
  chessui/chessboardparts/pieces.py
  chessui/chessboardparts/piecetypes/bishop.py
  chessui/chessboardparts/piecetypes/king.py
  chessui/chessboardparts/piecetypes/knight.py
  chessui/chessboardparts/piecetypes/pawn.py
  chessui/chessboardparts/piecetypes/queen.py
  chessui/chessboardparts/piecetypes/rook.py
  chessui/chessboardparts/tile.py
  chessui/chessboardparts/tiles.py
  chessui/design_ui/ChessApp_ui_look.png
  chessui/design_ui/ChessboardIndexing.jpg
  chessui/design_ui/UI_Design.txt
  chessui/inputbox.py
  chessui/main.py
  chessui/player_names.py
  chessui/scoreboard.py
  chessui/window.py
Labels: API, enhancement
